# Generated by Django 6.0.5 on 2026-05-15 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('weeks_pregnant', models.PositiveSmallIntegerField(default=24)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_set', models.BooleanField(default=False)),
                ('health_conditions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
