# Generated by Django 6.0.5 on 2026-05-31 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosevent',
            name='contacts_notified_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='offline_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('text', models.TextField()),
                ('mode', models.CharField(choices=[('ai', 'AI'), ('nurse', 'Nurse')], default='ai', max_length=16)),
                ('input_mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=16)),
                ('provider_id', models.PositiveIntegerField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='openai', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
