# Generated by Django 6.0.5 on 2026-05-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('tired', 'Tired'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('happy', 'Happy'), ('ok', 'OK')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__gt', '')), fields=('user', 'client_id'), name='unique_mood_client_id_per_user')],
            },
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('category', models.CharField(default='warning_signs', max_length=32)),
                ('symptoms', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('food_note', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__gt', '')), fields=('user', 'client_id'), name='unique_symptom_client_id_per_user')],
            },
        ),
    ]
